steps:
# Step 1: Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/chanoch-grocery:$COMMIT_SHA', '.']

# Step 2: Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/chanoch-grocery:$COMMIT_SHA']

# Step 3: Deploy the container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'chanoch-grocery' # Your Cloud Run service name
  - '--image'
  - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/chanoch-grocery:$COMMIT_SHA'
  - '--region'
  - 'northamerica-northeast2' # Your Cloud Run service region
  - '--allow-unauthenticated'
  - '--set-secrets'
  - 'GEMINI_API_KEY=${_SECRET_NAME}:latest'

# Add this 'options' block to specify logging behavior
options:
  logging: CLOUD_LOGGING_ONLY # This tells Cloud Build to use Cloud Logging for logs

substitutions:
  _SECRET_NAME: 'chanoch-grocery-api'

images:
- 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/chanoch-grocery:$COMMIT_SHA'
